const products = [
  {
    _id: "1",
    name: "PlayStation 5",
    image: "../images/ps5.jpg",
    description: "Playstation 5 description",
    brand: "Sony",
    category: "Electronics",
    price: 300.59,
    countInStock: 12,
    rating: 4,
    numReviews: 11,
  },
  {
    _id: "2",
    name: "Headphone",
    image: "../images/headphone.jpg",
    description: "Headphone description",
    brand: "Samsung",
    category: "Electronics",
    price: 99.59,
    countInStock: 12,
    rating: 3.5,
    numReviews: 20,
  },
  {
    _id: "3",
    name: "MacBook",
    image: "../images/macbook.jpg",
    description: "MacBook description",
    brand: "Apple",
    category: "Electronics",
    price: 1000.59,
    countInStock: 12,
    rating: 4,
    numReviews: 11,
  },
  {
    _id: "4",
    name: "Alexa",
    image: "../images/alexa.jpg",
    description: "Headphone description",
    brand: "Amazon",
    category: "Electronics",
    price: 99.59,
    countInStock: 12,
    rating: 3,
    numReviews: 20,
  },
];

export default products;
